service: breno-blog-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: api/hello
          method: get

plugins:
  - serverless-plugin-typescript
